# Generated by Django 5.2.6 on 2025-09-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='fastName',
            new_name='fristName',
        ),
        migrations.RenameField(
            model_name='dashboardmodel',
            old_name='fastName',
            new_name='fristtName',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='fastName',
            new_name='fristName',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='fastName',
            new_name='firsstName',
        ),
        migrations.RenameField(
            model_name='teachermodel',
            old_name='fastName',
            new_name='firstName',
        ),
    ]
