# Generated by Django 5.2.6 on 2025-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_fastname_contactmodel_fristname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='phoneNumber',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='dashboardmodel',
            old_name='phoneNumber',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='phoneNumber',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='phoneNumber',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
