# Generated by Django 5.2.6 on 2025-09-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_phonenumber_contactmodel_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='age',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='age',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='age',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='age',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='age',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
