# Generated by Django 5.2.6 on 2025-09-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_contactmodel_age_alter_dashboardmodel_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactModel',
        ),
        migrations.DeleteModel(
            name='dashboardModel',
        ),
        migrations.DeleteModel(
            name='employeeModel',
        ),
    ]
