# Generated by Django 5.2.6 on 2025-09-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_delete_contactmodel_delete_dashboardmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='departMent',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='firsstName',
            new_name='firstName',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
