# Generated by Django 5.2.6 on 2025-09-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_department_studentmodel_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='firstName',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='lastName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teachermodel',
            old_name='city',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='teachermodel',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teachermodel',
            old_name='lastName',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='age',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='emailAddress',
            field=models.EmailField(default=True, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='joining_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='emailAddress',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
