# Generated by Django 5.2.6 on 2025-09-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_rename_firstname_studentmodel_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='joining_Date',
            field=models.DateField(null=True),
        ),
    ]
